apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web-api
          image: localhost:5000/boot/web-api:1.0.1
          ports:
            - containerPort: 8080
